ClinicProject/Models/Patient.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ClinicProject.Models
{
    public class Patient
    {
        public Patient()
        {
            DateOfBirth = new DateTime(1992, 05, 20);
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [MaxLength(30),MinLength(3)]
        [RegularExpression("^[a-zA-Z'-']+$", ErrorMessage = "{0} can contain only letters and '-'! ")]
        public string FirstName { get; set; }
        [Required]
        [MaxLength(30),MinLength(3)]
        [RegularExpression("^[a-zA-Z'-']+$",ErrorMessage="{0} can contain only letters and '-' !")]
        public string LastName { get; set; }
        [Required]
        [StringLength(30)]
        public string Address { get; set; }
        [Required]
        [MaxLength(11),MinLength(11)]
        [RegularExpression("^[0-9]+$", ErrorMessage = "{0} can contain only digits!")]
        public string Pesel { get; set; }
        [Display(Name = "Date of Birth")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Required]
        public DateTime DateOfBirth { get; set; }
        [MaxLength(9),MinLength(9)]
        [RegularExpression("^[0-9]+$",ErrorMessage = "{0} can contain only digits!")]
        public string PhoneNumber { get; set; }       
        public virtual List<Visit> Visits { get; set; }

    }
}

ClinicProject/Models/PatientViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ClinicProject.Models
{
    public class PatientViewModel
    {
        public Patient Patient { get; set; }
        public IEnumerable<Visit> Visits { get; set; }
        public IEnumerable<MedicalExamination> MedicalExaminations { get; set; }
    }
}

ClinicProject/Controllers/PatientController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ClinicProject.Models;
using PagedList;

namespace ClinicProject.Controllers
{
    public class PatientController : Controller
    {
        private MyContext db = new MyContext();

        // GET: /Patient/
        public ActionResult Index(string sortOrder, string currentPeselFilter, string pesel, string currentLastNameFilter, string lastName, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSort = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSort = sortOrder == "Date" ? "Date_desc" : "Date";
            if (pesel != null)
                page = 1;
            else
                pesel = currentPeselFilter;
            if (lastName != null)
                page = 1;
            else
                lastName = currentLastNameFilter;

            ViewBag.CurrentLastNameFilter = lastName;
            ViewBag.CurrentPeselFilter = pesel;

            var patients = from p in db.Patients
                           select p;

            switch(sortOrder)
            {
                case "name_desc":
                    patients = patients.OrderByDescending(p => p.LastName);
                    break;
                case "Date":
                    patients = patients.OrderBy(p => p.DateOfBirth);
                    break;
                case "Date_desc":
                    patients = patients.OrderByDescending(p => p.DateOfBirth);
                    break;
                default:
                    patients = patients.OrderBy(p => p.LastName);
                    break;
            }

            if (!String.IsNullOrEmpty(pesel))
            {
                patients = patients.Where(s => s.Pesel.Contains(pesel));
            }
            if (!String.IsNullOrEmpty(lastName))
            {
                patients = patients.Where(s => s.LastName.Contains(lastName));
            }

            int pageSize = 10;
            int pageNumber = (page ?? 1);

            return View(patients.ToPagedList(pageNumber,pageSize));
        }

        // GET: /Patient/Details/5
        public async Task<ActionResult> Details(int? id, int? visitId)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
            {
                var viewModel = new PatientViewModel();
                viewModel.Patient = await db.Patients.Where(i => i.Id == id.Value).SingleOrDefaultAsync();
                if (viewModel.Patient == null)
                {
                    return HttpNotFound();
                }
                if (viewModel.Patient.Visits.Count != 0)
                {
                    viewModel.Visits = viewModel.Patient.Visits;
                    if (visitId != null)
                    {
                        ViewBag.VisitId = visitId.Value;
                        viewModel.MedicalExaminations = viewModel.Visits
                            .Where(i => i.Id == visitId.Value).SingleOrDefault().MedicalExaminations;
                    }
                }
                return View(viewModel);
            }
        }

        // GET: /Patient/Create
        public ActionResult Create()
        {
            var patient = new Patient();
            return View(patient);
        }

        // POST: /Patient/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include="Id,FirstName,LastName,Address,Pesel,DateOfBirth,PhoneNumber")] Patient patient)
        {            
            if (ModelState.IsValid)
            {
                db.Patients.Add(patient);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(patient);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult Select(int id)
        {
            return RedirectToAction("Create", "Visit", new { id = id });
        }     
    }
}

ClinicProject/Views/Patient/Create.cshtml
@model ClinicProject.Models.Patient

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Patient</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName)
                @Html.ValidationMessageFor(model => model.FirstName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName)
                @Html.ValidationMessageFor(model => model.LastName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address)
                @Html.ValidationMessageFor(model => model.Address)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Pesel, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pesel)
                @Html.ValidationMessageFor(model => model.Pesel)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfBirth, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfBirth)
                @Html.ValidationMessageFor(model => model.DateOfBirth)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber)
                @Html.ValidationMessageFor(model => model.PhoneNumber)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ClinicProject/Views/Patient/Details.cshtml
@model ClinicProject.Models.PatientViewModel

@{
    ViewBag.Title = "Patients and their medical history";
}

<h2>Patients and their medical history</h2>

<div>
    <h4>Patient</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            First Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Patient.FirstName)
        </dd>

        <dt>
            Last Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Patient.LastName)
        </dd>

        <dt>
            Address
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Patient.Address)
        </dd>

        <dt>
            Pesel
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Patient.Pesel)
        </dd>

        <dt>
            Date of Birth
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Patient.DateOfBirth)
        </dd>

        <dt>
            PhoneNumber
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Patient.PhoneNumber)
        </dd>

    </dl>
</div>
@if(Model.Visits != null)
{ 
    <div>
        <h4>Medical history of a selected patient</h4>
        <table class="table">
            <tr>
                <th></th>
                <th>
                    @Html.DisplayNameFor(model => model.Visits.First().Description)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Visits.First().Diagonose)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Visits.First().ExecuteDate)
                </th>
            </tr>
            @foreach (var item in Model.Visits)
            {
                string selectedRow = "";
                if(item.Id == ViewBag.VisitId)
                {
                    selectedRow = "success";
                }
            <tr class="@selectedRow">
                <td>
                    @Html.ActionLink("Details", "Details", new { id = Model.Patient.Id, visitId = item.Id })
                </td>
                <td>
                    @item.Description
                </td>
                <td>
                    @item.Diagonose
                </td>
                <td>
                    @item.ExecuteDate
                </td>
            </tr>
            }
        </table>
    </div>
}

@if (Model.MedicalExaminations != null)
{
    <div>
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.MedicalExaminations.FirstOrDefault().Description)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MedicalExaminations.FirstOrDefault().ExecutionDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MedicalExaminations.FirstOrDefault().Result)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MedicalExaminations.FirstOrDefault().Comment)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MedicalExaminations.FirstOrDefault().State)
                </th>
            </tr>
            @foreach(var item in Model.MedicalExaminations)
            { 
                <tr>
                    <td>
                        @item.Description
                    </td>
                    <td>
                        @item.ExecutionDate
                    </td>
                    <td>
                        @item.Result
                    </td>
                    <td>
                        @item.Comment
                    </td>
                    <td>
                        @item.State
                    </td>
                </tr>
            }
        </table>
    </div>
}
<p>
    <a href="javascript: history.go(-1)" class="btn btn-primary" >Go Back</a>
</p>

ClinicProject/Views/Patient/Index.cshtml
@model PagedList.IPagedList<ClinicProject.Models.Patient>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Patients";
}

<h2>Patients</h2>

    @Html.ActionLink("Create New", "Create")
    @using (Html.BeginForm("Index", "Patient", FormMethod.Get))
    {
    <p>
        Pesel: @Html.TextBox("Pesel",ViewBag.CurrentPeselFilter as string)
        LastName: @Html.TextBox("lastName", ViewBag.CurrentLastNameFilter as string)
        <input type="submit" value="Filter" class="btn-primary" />
    </p>    
    }

<table class="table table-hover" id="IndexTable">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().FirstName)
        </th>
        <th>
            @Html.ActionLink("Last Name", "Index", new { sortOrder = ViewBag.NameSort, currentPeselFilter = ViewBag.CurrentPeselFilter, currentLastNameFilter = ViewBag.CurrentLastNameFilter })
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().Pesel)
        </th>
        <th>
            @Html.ActionLink("Date of Birth", "Index", new { sortOrder = ViewBag.DateSort, currentPeselFilter = ViewBag.CurrentPeselFilter, currentLastNameFilter = ViewBag.CurrentLastNameFilter })
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstOrDefault().PhoneNumber)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Pesel)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateOfBirth)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PhoneNumber)
        </td>
        <td>
            @Html.ActionLink("Details", "Details", new { id = item.Id })|
            @Html.ActionLink("Select", "Select", new { id = item.Id })
        </td>
    </tr>
}

</table>
<br />

Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
            new { page, sortOrder = ViewBag.CurrentSort, currentPeselFilter = ViewBag.CurrentPeselFilter, currentLastNameFilter = ViewBag.CurrentLastNameFilter}))