ClinicProject/Models/MedicalExamination.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ClinicProject.Models
{
    public enum MedicalExaminationState
    {
        CanceledByTechnician, CanceledByChief, Done, Pending, Approved
    }
    public enum ExaminationType
    {
        Physical, Laboratory
    }
    public class MedicalExamination
    {
        public MedicalExamination()
        {
            State = MedicalExaminationState.Pending;
            ExecutionDate = null;
            EntryDate = DateTime.Now;
            AcceptanceDate = null;
            ChiefTechnicianId = null;
            LaboratoryTechnicianId = null;

        }
        public int Id { get; set; }
        
        public DateTime EntryDate { get; set; }

        public DateTime? ExecutionDate { get; set; }

        public DateTime? AcceptanceDate { get; set; }

        public string Description { get; set; }

        public MedicalExaminationState? State { get; set; }

        public string Result { get; set; }

        public string Comment { get; set; }

        public ExaminationType? Type { get; set; }
        [Required]
        public int? VisitId { get; set; }
        public virtual Visit Visit { get; set; }

        public int? LaboratoryTechnicianId { get; set; }
        public virtual LaboratoryTechnician LaboratoryTechnician { get; set; }

        public int? ChiefTechnicianId { get; set; }
        public virtual ChiefTechnician ChiefTechnician { get; set; }
        
        [ForeignKey("ExaminationDictionary")]
        public string Code { get; set; }
        public virtual ExaminationDictionary ExaminationDictionary { get; set; }
        
    }
}

ClinicProject/Models/MedicalExaminationsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ClinicProject.Models
{
    public class MedicalExaminationsViewModel
    {
        public IEnumerable<MedicalExamination> MedicalExaminations { get; set; }
        public string Role { get; set; }
    }
}

ClinicProject/Controllers/MedicalExaminationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ClinicProject.Models;
using Microsoft.AspNet.Identity;


namespace ClinicProject.Controllers
{
    public class MedicalExaminationController : Controller
    {
        private MyContext db = new MyContext();

        // GET: /MedicalExamination/
        public async Task<ActionResult> Index(MedicalExaminationState? medicalState)
        {
            var medicalexaminations = db.MedicalExaminations.Include(m => m.ChiefTechnician).Include(m => m.ExaminationDictionary).Include(m => m.LaboratoryTechnician).Include(m => m.Visit);
            medicalexaminations = from me in medicalexaminations
                                  where me.Type == ExaminationType.Laboratory
                                  select me;
            if (medicalState != null)
            {
                medicalexaminations = from me in medicalexaminations
                                      where me.State == medicalState
                                      orderby me.EntryDate
                                      select me;                  
            }
            var viewModel = new MedicalExaminationsViewModel();
            viewModel.MedicalExaminations = await medicalexaminations.ToListAsync();
            viewModel.Role = GetUser().Roles.First().Role.Name;
            List<MedicalExaminationState> states = new List<MedicalExaminationState>();
            states = Enum.GetValues(typeof(MedicalExaminationState)).Cast<MedicalExaminationState>().ToList();
            ViewBag.MedicalStates = new SelectList(states);
            return View(viewModel);
        }

        // GET: /MedicalExamination/Create
        [Authorize(Roles="Doctor")]
        public ActionResult Create(int? id)
        {
            ViewBag.Code = new SelectList(db.ExaminationDictionary, "Code", "Name");
            var types = Enum.GetValues(typeof(ExaminationType)).Cast<ExaminationType>().ToList();
            ViewBag.Type = new SelectList(types);
            MedicalExamination me = new MedicalExamination();
            if(id != null)
                me.VisitId = id.Value;
            return View(me);
        }

        // POST: /MedicalExamination/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Doctor")]
        public async Task<ActionResult> Create([Bind(Include="Id,EntryDate,Description,State,Result,Comment,Type,LaboratoryTechnicianId,ChiefTechnicianId,Code")] MedicalExamination medicalexamination,int? VisitId)
        {
            // to do implement validation !!!!!!
            if (VisitId != null) 
                medicalexamination.VisitId = VisitId.Value;
            if (medicalexamination.Type == ExaminationType.Physical)
                medicalexamination.State = MedicalExaminationState.Done;
            db.MedicalExaminations.Add(medicalexamination);
            await db.SaveChangesAsync();
            return RedirectToAction("Edit", "Visit", new { id = medicalexamination.VisitId});
        }

        // GET: /MedicalExamination/Edit/5
        [Authorize(Roles = "Technician")]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MedicalExamination medicalexamination = await db.MedicalExaminations.FindAsync(id);
            if (medicalexamination == null)
            {
                return HttpNotFound();
            }
            medicalexamination.ExecutionDate = DateTime.Now;
            return View(medicalexamination);
        }

        // POST: /MedicalExamination/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Technician")]
        public async Task<ActionResult> Edit([Bind(Include="Id,ExecutionDate,Result,Comment")] MedicalExamination medicalexamination)
        {
            var temp = (from me in db.MedicalExaminations
                        where me.Id == medicalexamination.Id
                        select me).Single();
            var user = GetUser();
            temp.ExecutionDate = DateTime.Now;
            temp.State = MedicalExaminationState.Done;
            temp.Result = medicalexamination.Result;
            temp.Comment = medicalexamination.Comment;
            temp.LaboratoryTechnicianId = (from w in db.Workers
                                          where w.FirstName == user.FirstName && w.LastName == user.LastName
                                          select w.Id).Single();
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private ApplicationUser GetUser()
        {
            var userId = User.Identity.GetUserId();
            var user = db.Users.Find(userId);
            if (user != null)
                return user;
            return null;
        }

        [Authorize(Roles ="ChiefTechnician,Technician")]
        public async Task<ActionResult> Cancel(int id, string role)
        {
            var examination = (from me in db.MedicalExaminations
                      where me.Id == id
                      select me).Single();
            if (role == "ChiefTechnicnian")
            {
                examination.State = MedicalExaminationState.CanceledByChief;
                examination.AcceptanceDate = DateTime.Now;
            }
            else
            {
                examination.State = MedicalExaminationState.CanceledByTechnician;
                examination.ExecutionDate = DateTime.Now;
            }
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        [Authorize(Roles = "ChiefTechnician")]
        public async Task<ActionResult> Approve(int id, string role)
        {
            var examination = (from me in db.MedicalExaminations
                               where me.Id == id
                               select me).Single();
            examination.State = MedicalExaminationState.Approved;
            examination.AcceptanceDate = DateTime.Now;
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }
}

ClinicProject/Views/MedicalExamination/Create.cshtml
@model ClinicProject.Models.MedicalExamination

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create","MedicalExamination",new {visitId = Model.VisitId},FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>MedicalExamination</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.EntryDate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EntryDate)
                @Html.ValidationMessageFor(model => model.EntryDate)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Type", null, new { @id = "Type" })
                @Html.ValidationMessageFor(model => model.Type)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>
        <div id="physical">
            <div class="form-group">
                @Html.LabelFor(model => model.Result, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Result)
                    @Html.ValidationMessageFor(model => model.Result)
                </div>
            </div>
        </div>

        <div id="laboratory">
            <div class="form-group">
                @Html.LabelFor(model => model.Code, "Code", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("Code", String.Empty)
                    @Html.ValidationMessageFor(model => model.Code)
                </div>
            </div>
        </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
}

<script type="text/javascript">
    $(function () {
        $('#laboratory').hide();
        $('#Type').change(function () {
            if ($(this).val() == 'Laboratory') {
                $('#laboratory').show();
                $('#physical').hide();

            } else {
                $('#laboratory').hide();
                $('#physical').show();

            }
        });
    });
</script>

ClinicProject/Views/MedicalExamination/Edit.cshtml
@model ClinicProject.Models.MedicalExamination

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>MedicalExamination</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.Code)

        <div class="form-group">
            @Html.LabelFor(model => model.ExecutionDate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExecutionDate)
                @Html.ValidationMessageFor(model => model.ExecutionDate)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Result, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Result)
                @Html.ValidationMessageFor(model => model.Result)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comment, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comment)
                @Html.ValidationMessageFor(model => model.Comment)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ClinicProject/Views/MedicalExamination/Index.cshtml
@model ClinicProject.Models.MedicalExaminationsViewModel

@{
    ViewBag.Title = "Medical Examinations";
}

<h2>Medical Examinations</h2>


<p class="text-right">Filter by Examination state: @Html.DropDownList("MedicalStates", String.Empty) </p>

<table class="table">
    <tr>
        <th>
            Examination code
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MedicalExaminations.FirstOrDefault().EntryDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MedicalExaminations.FirstOrDefault().ExecutionDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MedicalExaminations.FirstOrDefault().AcceptanceDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MedicalExaminations.FirstOrDefault().Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MedicalExaminations.FirstOrDefault().State)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MedicalExaminations.FirstOrDefault().Result)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MedicalExaminations.FirstOrDefault().Comment)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MedicalExaminations.FirstOrDefault().Type)
        </th>
        <th>
            Assigned Laboratory Technician
        </th>
        <th>
            Assigned Chief Technician
        </th>
        <th></th>
    </tr>

@foreach (var item in Model.MedicalExaminations) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ExaminationDictionary.Code)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EntryDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ExecutionDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AcceptanceDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.State)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Result)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Comment)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Type)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LaboratoryTechnician.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ChiefTechnician.FirstName)
        </td>
        <td>
            @if (Model.Role == "ChiefTechnician" && item.State == ClinicProject.Models.MedicalExaminationState.Done)
            {
                @Html.ActionLink("Cancel  ", "Cancel", new { id = item.Id, role = Model.Role });  
                @Html.ActionLink(" Approve", "Approve", new { id = item.Id, role = Model.Role });
            }
            else if(item.State == ClinicProject.Models.MedicalExaminationState.Pending)
            {
                @Html.ActionLink("Perform  ", "Edit",new { id = item.Id});  
                @Html.ActionLink(" Cancel", "Cancel", new { id = item.Id, role = Model.Role });
            }
        </td>
    </tr>
}

</table>

<script type="text/javascript">
    $(document).ready(function () {
        $('#MedicalStates').change(function () {
            var value = $(this).val();
            var _url = '@Url.Action("Index", "MedicalExamination")';
            $.ajax({
                url: _url,
                type: 'Get',
                cache: false,
                data: {
                    medicalState: value
                },
                success: function (data) {
                    $('body').html(data);
                }
            });
        });
    });
</script>