ClinicProject/Controllers/VisitController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web.Mvc;
using ClinicProject.Models;
using System.Text;
using Microsoft.AspNet.Identity;


namespace ClinicProject.Controllers
{
    public class VisitController : Controller
    {
        private MyContext db = new MyContext();

        // GET: /Visit/
        public async Task<ActionResult> Index(State? state)
        {
            // doctor should only see his visits 
            //eager loading
            var user = GetUser();
            var visits = db.Visits
                .Include(v => v.Patient)
                .Include(v => v.Registrant)
                .Include(v => v.Doctor)
                .OrderBy(v => v.RegistryDate);
            var viewModel = new VisitViewModel();
            if (user.Roles.First().Role.Name == "Doctor")
            {
                visits = from v in visits
                         where v.Doctor.LastName == user.LastName && v.Doctor.FirstName == user.FirstName
                         orderby v.RegistryDate
                         select v;
            }
            if (state != null && state != State.All)
            {
                visits = from v in visits
                         where v.State == state.Value
                         orderby v.RegistryDate
                         select v;
            }
            visits = visits.OrderByDescending(v => v.RegistryDate);
            viewModel.Visits = await visits.ToListAsync();
            viewModel.Role = user.Roles.First().Role.Name;
            var states = new List<State>();
            states = Enum.GetValues(typeof(State)).Cast<State>().ToList();
            ViewBag.States = new SelectList(states);
            return View(viewModel);
        }

        // GET: /Visit/Create
        [Authorize(Roles = "Registrant")]
        public ActionResult Create(int? id)
        {
            if (id != null)
                ViewBag.PatientId = GetPatientInfo(id);
            ViewBag.DoctorId = new SelectList(db.Workers.OfType<Doctor>(), "Id", "FirstName");
            return View(new Visit());
        }

        // POST: /Visit/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Registrant")]
        public async Task<ActionResult> Create([Bind(Include="Id,RegistryDate,State,ExecuteDate,Description,Diagonose,DoctorId")] Visit visit, int? id)
        {
            if(id != null)
                visit.PatientId = id.Value;
            if (ModelState.IsValid)
            {
                var user = GetUser();
                int registrantId = (from w in db.Workers
                                    where w.FirstName == user.FirstName && w.LastName == user.LastName
                                    select w.Id).Single();
                visit.RegistrantId = registrantId;
                db.Visits.Add(visit);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            if (id != null)
                ViewBag.PatientId = GetPatientInfo(id);
            ViewBag.DoctortId = new SelectList(db.Workers.OfType<Doctor>(), "Id", "FirstName", visit.DoctorId);
            return View(visit);
        }

        // GET: /Visit/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var visit = await db.Visits.FindAsync(id);
            if (visit == null)
            {
                return HttpNotFound();
            }
            ViewBag.RegistrantId = new SelectList(db.Workers.OfType<Registrant>(), "Id", "FirstName", visit.RegistrantId);
            ViewBag.DoctortId = new SelectList(db.Workers.OfType<Doctor>(), "Id", "FirstName", visit.DoctorId);
            return View(visit);
        }

        // POST: /Visit/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Description,Diagonose")] Visit visit)
        {
            if (ModelState.IsValid)
            {
                var temp = db.Visits.SingleOrDefault(v => v.Id == visit.Id);
                temp.Description = visit.Description;
                temp.Diagonose = visit.Diagonose;
                temp.ExecuteDate = DateTime.Now;
                temp.State = State.Ended;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(visit);
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        private string GetPatientInfo(int? id)
        {
            var patient = (from p in db.Patients
                          where p.Id == id
                          select p).Single();
            StringBuilder temp = new StringBuilder();
            temp.Append(patient.FirstName);
            temp.Append(" ");
            temp.Append(patient.LastName);
            temp.Append(" ");
            temp.Append(patient.Pesel);
            return temp.ToString();
        }

        [Authorize(Roles="Doctor")]
        public async Task<ActionResult> Start(int? id)
        {
            var visit = from v in db.Visits
                        where v.Id == id.Value
                        select v;
            if(visit.Single().State == State.Registred)
                visit.Single().State = State.InProgress;
            await db.SaveChangesAsync();
            return RedirectToAction("Edit", new { id = id.Value });
        }

        [Authorize(Roles = "Registrant")]
        public async Task<ActionResult> Cancel(int? id)
        {
            var visit = from v in db.Visits
                        where v.Id == id.Value
                        select v;
            if (visit.Single().State == State.Registred) // u can only cancel the registred ones!
                visit.Single().State = State.Canceled;
            visit.Single().ExecuteDate = DateTime.Now;
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        private ApplicationUser GetUser()
        {
            var userId = User.Identity.GetUserId();
            var user = db.Users.Find(userId);
            if (user != null)
                return user;
            return null;
        }
        public ActionResult GetPatientByName(string firstName, string lastName)
        {
            var patient = (from p in db.Patients
                           where p.FirstName == firstName && p.LastName == lastName
                           select p).SingleOrDefault();
            return RedirectToAction("Details", "Patient", new { id = patient.Id });
        }

        public ActionResult AddExamination(int? id)
        {
            return RedirectToAction("Create", "MedicalExamination", new { id = id.Value });
        }

        public async Task<ActionResult> CancelVisit(int id)
        {
            var visit = await db.Visits.SingleOrDefaultAsync(v => v.Id == id);

            visit.State = State.Canceled;
            visit.Description = "Canceled by Doctor";
            visit.ExecuteDate = DateTime.Now;

            await db.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        public ActionResult UpdateDoctorList(string date)
        {
            var dateTime = Convert.ToDateTime(date);
            var model = new Tuple<Visit, DateTime>(new Visit(), dateTime);
            return PartialView("_DoctorList", model);
        }
    }
}

ClinicProject/Controllers/WorkerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ClinicProject.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace ClinicProject.Controllers
{
    public class WorkerController : Controller
    {
        private MyContext db = new MyContext();

        // GET: /Worker/
        public async Task<ActionResult> Index()
        {
            var workers = await db.Workers.ToListAsync();
            var ret = from w in workers
                      orderby w.GetType().Name
                      select w;
            return View(ret);
        }

        // GET: /Worker/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Worker worker = await db.Workers.FindAsync(id);
            if (worker == null)
            {
                return HttpNotFound();
            }
            return View(worker);
        }

        // GET: /Worker/Create
        public ActionResult Create()
        {
            List<string> roleNames = new List<string>{"Registrant", "Doctor", "Technician", "ChiefTechnician" };
            //roleNames.Sort();
            ViewBag.Role = new SelectList(roleNames);
            return View();
        }

        // POST: /Worker/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(FormCollection fc)
        {
            string role = fc["Role"];
            string firstName = fc["FirstName"];
            string lastName = fc["LastName"];
            string hireDate = fc["HireDate"];
            string dob = fc["DateOfBirth"];
            string password = fc["Password"];
            string userName = fc["UserName"];
            if (ModelState.IsValid)
            {
                // user creation
                var store = new UserStore<ApplicationUser>(db);
                var manager = new UserManager<ApplicationUser>(store);
                var user = new ApplicationUser { UserName = userName };
                user.FirstName = firstName;
                user.LastName = lastName;
                var hasher = new PasswordHasher();
                var hashedPassword = hasher.HashPassword(password);
                user.PasswordHash = hashedPassword;

                manager.Create(user);
                manager.AddToRole(user.Id, role);
                if (role == "Doctor")
                {
                    string license = fc["License"];
                    string specialty = fc["Specialty"];
                    Doctor doctor = 
                        new Doctor(firstName,lastName,DateTime.Parse(dob),DateTime.Parse(hireDate),license,specialty);
                    db.Workers.Add(doctor);
                }
                else if (role == "Registrant")
                {
                    Registrant registrant = new Registrant(firstName, lastName, DateTime.Parse(dob), DateTime.Parse(hireDate));
                    db.Workers.Add(registrant);
                }
                else if (role == "Technician")
                {
                    LaboratoryTechnician lt = new LaboratoryTechnician(firstName, lastName, DateTime.Parse(dob), DateTime.Parse(hireDate));
                    db.Workers.Add(lt);
                }
                else
                {
                    ChiefTechnician ct = new ChiefTechnician(firstName, lastName, DateTime.Parse(dob), DateTime.Parse(hireDate));
                    db.Workers.Add(ct);
                }
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View();
        }

        // GET: /Worker/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Worker worker = await db.Workers.FindAsync(id);
            if (worker == null)
            {
                return HttpNotFound();
            }
            return View(worker);
        }

        // POST: /Worker/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include="Id,FirstName,LastName,DateOfBirth,HireDate,Status")] Worker worker)
        {
            if (ModelState.IsValid)
            {
                db.Entry(worker).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(worker);
        }

        // GET: /Worker/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Worker worker = await db.Workers.FindAsync(id);
            if (worker == null)
            {
                return HttpNotFound();
            }
            return View(worker);
        }

        // POST: /Worker/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Worker worker = await db.Workers.FindAsync(id);
            db.Workers.Remove(worker);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult GetPartial()
        {
            return PartialView("_DoctorPartial",db.Workers);
        }
    }
}

ClinicProject/Views/Shared/_DoctorList.cshtml
@using ClinicProject.Helpers
@model Tuple<ClinicProject.Models.Visit, DateTime>

@{
    var visit = Model.Item1;
    var date = Model.Item2;
}           

@Html.DropDownDoctorsFor(model => visit.DoctorId, new { @class = "col-sm-7 form-control" }, "DoctorId", date)

ClinicProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Clinic Systems</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Clinic System", "Index", "Home", null, new { @class = "navbar-brand" })
                
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Visits","Index","Visit")</li>
                    <li>@Html.ActionLink("Workers","Index","Worker")</li>
                    <li>@Html.ActionLink("Medical Examinations", "Index", "MedicalExamination")</li>
                    <li>@Html.ActionLink("Examination Dictionary", "Index", "ExaminationDictionary")</li>*@
                   @Html.Partial("_Menu")

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Clinic System</p>
        </footer>
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>

ClinicProject/Views/Shared/_Menu.cshtml
@{
    var menus = new[]
    {
        new {LinkText = "Home", ActionName = "Index", ControllerName = "Home", Roles = "All" },
        new {LinkText = "About", ActionName = "Index", ControllerName = "Home", Roles = "All" },
        new {LinkText = "Contact", ActionName = "Index", ControllerName = "Home", Roles = "All" },
        new {LinkText = "Manage Workers", ActionName = "Index", ControllerName = "Worker", Roles = "Admin" },
        new {LinkText = "Manage examinations and its prices", ActionName = "Index", ControllerName = "ExaminationDictionary", Roles = "Admin" },
        new {LinkText = "Medical Examinations", ActionName = "Index", ControllerName = "MedicalExamination", Roles = "ChiefTechnician,Technician" },
        new {LinkText = "Manage visits", ActionName = "Index", ControllerName = "Visit", Roles = "Registrant,Doctor" }

    };
}

@if (HttpContext.Current.User.Identity.IsAuthenticated)
{
    var links = from item in menus
               select item;
    if (User.IsInRole("Admin"))
    {
        links = from item in menus
                    where item.Roles.Contains("Admin") || item.Roles.Contains("All")
                    select item;
    }
    else if (User.IsInRole("Doctor"))
    {
        links = from item in menus
                where item.Roles.Contains("Doctor") || item.Roles.Contains("All")
                select item;
    }
    else if (User.IsInRole("Registrant"))
    {
        links = from item in menus
                where item.Roles.Contains("Registrant") || item.Roles.Contains("All")
                select item;
    }
    else if (User.IsInRole("Technician"))
    {
        links = from item in menus
                where item.Roles.Contains("Technician") || item.Roles.Contains("All")
                select item;
    }
    else
    {
        links = from item in menus
                where item.Roles.Contains("ChiefTechnician") || item.Roles.Contains("All")
                select item;
    }
    foreach (var link in links)
    {
        @:
        <li> @Html.ActionLink(link.LinkText, link.ActionName, link.ControllerName)</li>
    }
}
else
{
    var links = from item in menus
                where item.Roles.Split(new String[] { "," }, StringSplitOptions.RemoveEmptyEntries)
                .Any(x => new String[] { "All", "Anonymous" }.Contains(x))
                select item;
    foreach (var link in links)
    {
        @:
        <li> @Html.ActionLink(link.LinkText, link.ActionName, link.ControllerName)</li>
    }
}